export default [
  {
    id: 'abc123',
    name: 'Alfie A',
    email: 'aabrams@aol.com',
    color: 'green',
    dateAdded: 1310669017000,
    status: 'QUEUEING',
    fileName: 'statue_of_lib.stl',
    position: 100,
    comments: '',
    location: 'downtown',
  },
  {
    id: 'def456',
    name: 'Betsy',
    email: 'betsy.brahm@bombbomb.com',
    color: 'red',
    dateAdded: 1566226114628,
    status: 'QUEUEING',
    fileName: 'spaceneedle.stl',
    position: 200,
    comments: '',
    location: 'downtown',
  },
  {
    id: 'ghi789',
    name: 'Cee Cee Chaplin',
    email: 'cdef@gmail.com',
    color: 'blue',
    dateAdded: 1566226214092,
    status: 'QUEUEING',
    fileName: 'stlArch.stl',
    position: 300,
    comments: '',
    location: 'downtown',
  },
  {
    id: 'ghi789',
    name: 'Cee Cee Chaplin',
    email: 'cdef@gmail.com',
    color: 'blue',
    dateAdded: 1566033724000,
    status: 'QUEUEING',
    fileName: 'ORFalls.stl',
    position: 400,
    comments: '',
    location: 'downtown',
  },
  {
    id: 'jkl012',
    name: 'Darius',
    email: 'ddunkin@dsu.edu',
    color: 'green',
    dateAdded: 1566228092314,
    status: 'PRINTING',
    fileName: 'CalRedwoods.stl',
    position: 500,
    comments: '',
    location: 'downtown',
  },
  {
    id: 'mno345',
    name: 'Emmett Emerson',
    email: 'ethoreson@plu.edu',
    color: 'red',
    dateAdded: 1567461346570,
    status: 'QUEUEING',
    fileName: 'MultnomahXDL.stl',
    position: 600,
    comments: 'any color is fine',
    location: 'downtown',
  },
  {
    id: 'pqr678',
    name: 'F. Franklin',
    email: 'fff@aol.com',
    color: 'white',
    dateAdded: 1567461445947,
    status: 'PRINTING',
    fileName: 'Liberty__Bell.stl',
    position: 700,
    comments: 'thanks for printing this',
    location: 'downtown',
  },
  {
    id: 'stu901',
    name: 'Gina',
    email: 'linettig@gmail.com',
    color: 'red',
    dateAdded: 1567461558104,
    status: 'PRINTING',
    fileName: 'BrooklynBridge.stl',
    position: 800,
    comments: '',
    location: 'downtown',
  },
];
