/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idealab;

import org.junit.Test;
import static org.junit.Assert.*;

public class IdeaLabMainTest {
    @Test public void testAppHasAGreeting() {
        // Dummy test
        assert true;
    }
}
