export default [
  {
    name: 'Alfie A',
    email: 'aabrams@aol.com',
    password: 'password',
    location: 'downtown',
    role: 'Admin',
  },
  {
    name: 'Betsy',
    email: 'betsy.brahm@bombbomb.com',
    password: 'password',
    location: 'downtown',
    role: 'Admin',
  },
  {
    name: 'Cee Cee Chaplin',
    email: 'cdef@gmail.com',
    password: 'password',
    location: 'downtown',
    role: 'Staff',
  },
  {
    name: 'Darius',
    email: 'ddunkin@dsu.edu',
    password: 'password',
    location: 'downtown',
    role: 'Staff',
  },
  {
    name: 'Emmett Emerson',
    email: 'ethoreson@plu.edu',
    password: 'password',
    location: 'downtown',
    role: 'Admin',
  },
  {
    name: 'F. Franklin',
    email: 'fff@aol.com',
    password: 'password',
    location: 'downtown',
    role: 'Admin',
  },
  {
    name: 'Gina',
    email: 'linettig@gmail.com',
    password: 'password',
    location: 'downtown',
    role: 'Staff',
  },
];
