export default
[
     {
         id: 'abc123',
         name: 'Alfie A',
         email: 'aabrams@aol.com',
         color: 'green',
         dateAdded: 1310669017000,
         status: 'QUEUEING',
         fileName: 'statue_of_lib.stl',
         position: 100,
         comments: '',
     },
     {
        id: 'def456',
        name: 'Betsy',
        email: 'betsy.brahm@bombbomb.com',
        color: 'red',
        dateAdded: 1566226114628,
        status: 'QUEUEING',
        fileName: 'spaceneedle.stl',
        position: 200,
        comments: '',
    },
    {
        id: 'ghi789',
        name: 'Cee Cee Chaplin',
        email: 'cdef@gmail.com',
        color: 'blue',
        dateAdded: 1566226214092,
        status: 'QUEUEING',
        fileName: 'stlArch.stl',
        position: 300,
        comments: '',
    },
    {
        id: 'ghi789',
        name: 'Cee Cee Chaplin',
        email: 'cdef@gmail.com',
        color: 'blue',
        dateAdded: 1566033724000,
        status: 'QUEUEING',
        fileName: 'ORFalls.stl',
        position: 400,
        comments: '',
    },
    {
        id: 'jkl012',
        name: 'Darius',
        email: 'ddunkin@dsu.edu',
        color: 'green',
        dateAdded: 1566228092314,
        status: 'PRINTING',
        fileName: 'CalRedwoods.stl',
        position: 500,
        comments: '',
    },
 ];