/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package idealab;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class IdeaLabMain {

    @Autowired
    public static void main(String[] args) {
        SpringApplication.run(IdeaLabMain.class, args);
    }
}
